#!/usr/bin/python
# To add a series you need the series ID from the search script

import requests, json
import urllib
import sys

vars = {}
vars['Cmd'] = 'add'
vars['StartPadding'] = '0'
# Use the imput for search
try:
	vars['SeriesID'] = sys.argv[1]
except:
	print "\naddseries <seriesID>\n"
	print "SeriesID can be obtained using the search script\n\n"
	exit()

r=requests.get('http://hdhomerun/discover.json')
vars['DeviceAuth'] = r.json()['DeviceAuth']

qstring = urllib.urlencode(vars)
url = "https://api.hdhomerun.com/api/recording_rules?" + qstring
print url

r = requests.get(url)
print r.text
#j = r.json()
#for recording in j:
#	print recording["SeriesID"] + ': ' + recording["Title"]
