#!/usr/bin/python
import requests, json
import urllib
import sys
import time

vars = {}
r=requests.get('http://hdhomerun/discover.json')
vars['DeviceAuth'] = r.json()['DeviceAuth']
qstring = urllib.urlencode(vars)
print qstring
url = 'https://api.hdhomerun.com/api/recording_rules?' + qstring
r = requests.get(url)
t = r.json()

for task in t:
	print task["RecordingRuleID"] + ' / ' + task["SeriesID"] + ': ' + task["Title"]
	vars['SeriesID'] = task["SeriesID"]
	qstring = urllib.urlencode(vars)
	url = "https://api.hdhomerun.com/api/episodes?" + qstring
	#print url
	r = requests.get(url)
	if r.text == "null":
		print "*** NO UPCOMING EPISODES ***"
		continue
	#print r.text
	j = r.json()
	for recording in j:
		#print recording
		try:
			etitle = recording["EpisodeTitle"]
		except:
			etitle =  task["Title"]
		stime = time.strftime( "%a, %d %b %Y %H:%M", time.localtime(recording["StartTime"]) )
		etime = time.strftime( "%H:%M", time.localtime(recording["EndTime"]) )
		print stime + '-' + etime, recording["ChannelNumber"], recording["Title"] + ': ' + etitle
