#!/bin/bash
# Print json for upcoming episodes
deviceAuth=`curl --silent http://hdhomerun/discover.json | sed "s/.*DeviceAuth...//" | sed "s/.,.*$//"`
for task in `curl --silent https://api.hdhomerun.com/api/recording_rules?DeviceAuth=$deviceAuth | grep SeriesID | sed "s/.*SeriesID....//" | sed "s/.,.*$//"`
do 
	resp=`curl --silent "https://api.hdhomerun.com/api/episodes?DeviceAuth=$deviceAuth&SeriesID=$task"`
	if [ "$resp" != "null" ]; then
	#	echo $resp | python -mjson.tool
	# This only prints the first entry, can't iterate through json
		title=`echo $resp | sed "s/^.*\"Title\"...//" | sed "s/\",.*$//"`
		channel=`echo $resp | sed "s/^.*ChannelNumber\"...//" | sed "s/\",.*$//"`
		eairdate=`echo $resp | sed "s/^.*StartTime...//" | sed "s/,.*$//"`
		airdate=`date -d @$eairdate`
		echo $airdate $channel $title
	fi
done

