#!/usr/bin/python
import requests, json
import urllib
import sys

vars = {}
# Get the search string from the command-line
try:
	vars['Search'] = sys.argv[1]
except:
	print "\nsearch <searchstring>\n"
	print "Use quotes for a multi-word search string\n\n"
	exit()

r=requests.get('http://hdhomerun/discover.json')
vars['DeviceAuth'] = r.json()['DeviceAuth']

qstring = urllib.urlencode(vars)
url = "https://api.hdhomerun.com/api/search?" + qstring
#print url
r = requests.get(url)
#print r.text
j = r.json()
for recording in j:
	print recording["SeriesID"] + ': ' + recording["Title"]
